In [15]:
# Jangan lupa download chromedriver trus tempatin di directory 
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import pandas as pd

# Set the path to the ChromeDriver executable
webdriver_path = "path file chromedriver kalian"  # ganti path file chromdriver kalian

# Set up the ChromeDriver service
service = Service(webdriver_path)

# Set up the Chrome options?
options = webdriver.ChromeOptions()

options.add_argument("--incognito") #buat buka browser incognito
options.add_argument('--disable-notifications') #disable notif twitter kalo pertama buka 
options.add_argument("--pageLoadStrategy=none")

# Create a new instance of the Chrome driver
driver = webdriver.Chrome(service=service, options=options)
driver.get("https://twitter.com/i/trends")

# Ini ambil datanya dari website di atas
trends = driver.find_elements(By.XPATH, '//div[@dir="ltr"]//span[@class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0"]')

# Looping datanya terus masukin ke list
data_trend = []
for trend in trends:
    data_trend.append(trend.text)

# Ambil yang dibutuhin aja     
data_trend = data_trend[5:]

# Split datanya 
def split_list(lst, size):
    return [lst[i:i+size] for i in range(0, len(lst), size)]
my_list = data_trend
sublists = split_list(my_list, 3)

# Tambahin nama kolom biar cakep
columns = ['Location', 'Trending', 'Volume']
data = pd.DataFrame(sublists, columns=columns)
driver.quit()
data = data[:20]

# kalo mau save datanya 
data.to_excel("trend_twitter.xlsx")
data



# kodingan dibawah ini dibuat kalau ada trending topic yang mengadung emoticon hehe
#divider = [x for x in data_trend if 'Trending' in x]

#sublists = [[]]
#for item in data_trend:
#    if any(div in item for div in divider):
#        sublists.append([])
#    sublists[-1].append(item)

#print("Sublists:", sublists)

#coba = sublists[1:20]

#pd.DataFrame(coba)

                    Location                Trending        Volume
0      Trending in Indonesia                   Nanas    13K Tweets
1      Trending in Indonesia            Pasutri Gaje  29.2K Tweets
2      Trending in Indonesia                   Rendy  27.3K Tweets
3      Trending in Indonesia                    Rabu  17.2K Tweets
4          Sports · Trending                  Asnawi  13.8K Tweets
5   Entertainment · Trending             Raffi Ahmad    15K Tweets
6      Trending in Indonesia  ALHAMDULILLAH YA ALLAH  7,869 Tweets
7      Technology · Trending                   Gojek  20.8K Tweets
8      Trending in Indonesia                    SNBT  45.5K Tweets
9           Music · Trending      LEE JENO THANK YOU  2,580 Tweets
10     Trending in Indonesia                    Geli  8,850 Tweets
11     Trending in Indonesia        #idolyfepanaroma  23.4K Tweets
12     Trending in Indonesia                  Adelia  16.6K Tweets
13     Trending in Indonesia               Inisial R  3,378 Tweets
14     Trending in Indonesia                    UTBK  16.4K Tweets
15     Trending in Indonesia                 Webtoon  25.5K Tweets
16     Trending in Indonesia               Typingnya  16.8K Tweets
17     Trending in Indonesia                   FK UI  6,672 Tweets
18     Trending in Indonesia                    Maba    20K Tweets
19     Trending in Indonesia                   Suami  53.7K Tweets

In [14]:
divider = [x for x in data_trend if 'Trending' in x]

sublists = [[]]
for item in data_trend:
    if any(div in item for div in divider):
        sublists.append([])
    sublists[-1].append(item)

print("Sublists:", sublists)

coba = sublists[1:20]

pd.DataFrame(coba)

Sublists: [[], ['Trending in Indonesia', 'Syahnaz', '49.5K Tweets'], ['Trending in Indonesia', 'Nanas', '12.9K Tweets'], ['Trending in Indonesia', 'Pasutri Gaje', '29K Tweets'], ['Trending in Indonesia', 'Rendy', '27.2K Tweets'], ['Entertainment · Trending', 'Raffi Ahmad', '14.9K Tweets'], ['Sports · Trending', 'Asnawi', '13.6K Tweets'], ['Trending in Indonesia', '1 L0ve yOu', ' sO', ' mUcH', '3,122 Tweets'], ['Trending in Indonesia', 'ALHAMDULILLAH YA ALLAH', '7,862 Tweets'], ['Technology · Trending', 'Gojek', '20.6K Tweets'], ['Trending in Indonesia', 'SNBT', '45.3K Tweets'], ['Trending in Indonesia', 'Inisial R', '3,222 Tweets'], ['Trending in Indonesia', 'Rabu', '17K Tweets'], ['Music · Trending', 'LEE JENO THANK YOU', '2,579 Tweets'], ['Trending in Indonesia', 'Geli', '8,711 Tweets'], ['Trending in Indonesia', 'Adelia', '16.4K Tweets'], ['Trending in Indonesia', 'UTBK', '16.3K Tweets'], ['Trending in Indonesia', 'Typingnya', '16.7K Tweets'], ['Trending in Indonesia', 'FK UI', '6,614 Tweets'], ['Trending in Indonesia', 'Webtoon', '25.3K Tweets'], ['Trending in Indonesia', '#idolyfepanaroma', '23.4K Tweets', 'New to Twitter?', 'Sign up now to get your own personalized timeline!', 'Sign up with Apple', 'Create account', 'Terms of Service', 'Privacy Policy', 'Cookie Use.', 'More', '© 2023 X Corp.']]

,0,1,2,3,4
0,Trending in Indonesia,Syahnaz,49.5K Tweets,None,None
1,Trending in Indonesia,Nanas,12.9K Tweets,None,None
2,Trending in Indonesia,Pasutri Gaje,29K Tweets,None,None
3,Trending in Indonesia,Rendy,27.2K Tweets,None,None
4,Entertainment · Trending,Raffi Ahmad,14.9K Tweets,None,None
5,Sports · Trending,Asnawi,13.6K Tweets,None,None
6,Trending in Indonesia,1 L0ve yOu,sO,mUcH,"3,122 Tweets"
7,Trending in Indonesia,ALHAMDULILLAH YA ALLAH,"7,862 Tweets",None,None
8,Technology · Trending,Gojek,20.6K Tweets,None,None
9,Trending in Indonesia,SNBT,45.3K Tweets,None,None
10,Trending in Indonesia,Inisial R,"3,222 Tweets",None,None
11,Trending in Indonesia,Rabu,17K Tweets,None,None
12,Music · Trending,LEE JENO THANK YOU,"2,579 Tweets",None,None
13,Trending in Indonesia,Geli,"8,711 Tweets",None,None
14,Trending in Indonesia,Adelia,16.4K Tweets,None,None
15,Trending in Indonesia,UTBK,16.3K Tweets,None,None
16,Trending in Indonesia,Typingnya,16.7K Tweets,None,None
17,Trending in Indonesia,FK UI,"6,614 Tweets",None,None
18,Trending in Indonesia,Webtoon,25.3K Tweets,None,None